 var specialsURLs = ["http://albuquerque.porschedealer.com/specials/",
"http://autogallery.porschedealer.com/specials/",
"http://bakersfield.porschedealer.com/specials/",
"http://bellevue.porschedealer.com/specials/",
"http://bend.porschedealer.com/specials/",
"http://boise.porschedealer.com/specials/",
"http://carlsen.porschedealer.com/specials/",
"http://colorado-springs.porschedealer.com/specials/",
"http://downtown-la.porschedealer.com/specials/",
"http://ed-carroll.porschedealer.com/specials/",
"http://fremont.porschedealer.com/specials/",
"http://hawaii.porschedealer.com/specials/",
"http://livermore.porschedealer.com/specials/",
"http://mckenna.porschedealer.com/specials/",
"http://monterey.porschedealer.com/specials/",
"http://newport-beach.porschedealer.com/specials/",
"http://niello.porschedealer.com/specials/",
"http://porschefresno.com/specials/",
"http://porschesantabarbara.com/specials/",
"http://rancho-mirage.porschedealer.com/specials/",
"http://reno.porschedealer.com/specials/",
"http://rusnak-pasadena.porschedealer.com/specials/",
"http://rusnak-westlake.porschedealer.com/specials/",
"http://scottsdale.porschedealer.com/specials/",
"http://sonnenporsche.com/specials/",
"http://spokane.porschedealer.com/specials/",
"http://stevens-creek.porschedealer.com/specials/",
"http://stevinson.porschedealer.com/specials/",
"http://tucson.porschedealer.com/specials/",
"https://bellingham.porschedealer.com/specials/",
"https://beverlyhillsporsche.com/specials/",
"https://burlingame.porschedealer.com/specials/",
"https://chandler.porschedealer.com/specials/",
"https://circleporsche.com/specials/",
"https://gaudinporschelv.com/specials/",
"https://hoehnporsche.com/specials/",
"https://porschelehi.com/specials/",
"https://porscheofanchorage.com/specials/",
"https://porscheofsandiego.com/specials/",
"https://porscheoftacoma.com/specials/",
"https://porschesaltlakecity.com/specials/",
"https://porschesouthbay.com/specials/",
"https://prestigeimportsporsche.com/specials/",
"https://riverside.porschedealer.com/specials/",
"https://sunsetporsche.com/specials/",
"https://walnutcreek.porschedealer.com/specials/",

//New Specials URLs
"http://albuquerque.porschedealer.com/specials/new/",
"http://autogallery.porschedealer.com/specials/new/",
"http://bakersfield.porschedealer.com/specials/new/",
"http://bellevue.porschedealer.com/specials/new/",
"http://bend.porschedealer.com/specials/new/",
"http://boise.porschedealer.com/specials/new/",
"http://carlsen.porschedealer.com/specials/new/",
"http://colorado-springs.porschedealer.com/specials/new/",
"http://downtown-la.porschedealer.com/specials/new/",
"http://ed-carroll.porschedealer.com/specials/new/",
"http://fremont.porschedealer.com/specials/new/",
"http://hawaii.porschedealer.com/specials/new/",
"http://livermore.porschedealer.com/specials/new/",
"http://mckenna.porschedealer.com/specials/new/",
"http://monterey.porschedealer.com/specials/new/",
"http://newport-beach.porschedealer.com/specials/new/",
"http://niello.porschedealer.com/specials/new/",
"http://porschefresno.com/specials/new/",
"http://porschesantabarbara.com/specials/new/",
"http://rancho-mirage.porschedealer.com/specials/new/",
"http://reno.porschedealer.com/specials/new/",
"http://rusnak-pasadena.porschedealer.com/specials/new/",
"http://rusnak-westlake.porschedealer.com/specials/new/",
"http://scottsdale.porschedealer.com/specials/new/",
"http://sonnenporsche.com/specials/new/",
"http://spokane.porschedealer.com/specials/new/",
"http://stevens-creek.porschedealer.com/specials/new/",
"http://stevinson.porschedealer.com/specials/new/",
"http://tucson.porschedealer.com/specials/new/",
"https://bellingham.porschedealer.com/specials/new/",
"https://beverlyhillsporsche.com/specials/new/",
"https://burlingame.porschedealer.com/specials/new/",
"https://chandler.porschedealer.com/specials/new/",
"https://circleporsche.com/specials/new/",
"https://gaudinporschelv.com/specials/new/",
"https://hoehnporsche.com/specials/new/",
"https://porschelehi.com/specials/new/",
"https://porscheofanchorage.com/specials/new/",
"https://porscheofsandiego.com/specials/new/",
"https://porscheoftacoma.com/specials/new/",
"https://porschesaltlakecity.com/specials/new/",
"https://porschesouthbay.com/specials/new/",
"https://prestigeimportsporsche.com/specials/new/",
"https://riverside.porschedealer.com/specials/new/",
"https://sunsetporsche.com/specials/new/",
"https://walnutcreek.porschedealer.com/specials/new/",
//
// //Used Specials URLs
"http://albuquerque.porschedealer.com/specials/used/",
"http://autogallery.porschedealer.com/specials/used/",
"http://bakersfield.porschedealer.com/specials/used/",
"http://bellevue.porschedealer.com/specials/used/",
"http://bend.porschedealer.com/specials/used/",
"http://boise.porschedealer.com/specials/used/",
"http://carlsen.porschedealer.com/specials/used/",
"http://colorado-springs.porschedealer.com/specials/used/",
"http://downtown-la.porschedealer.com/specials/used/",
"http://ed-carroll.porschedealer.com/specials/used/",
"http://fremont.porschedealer.com/specials/used/",
"http://hawaii.porschedealer.com/specials/used/",
"http://livermore.porschedealer.com/specials/used/",
"http://mckenna.porschedealer.com/specials/used/",
"http://monterey.porschedealer.com/specials/used/",
"http://newport-beach.porschedealer.com/specials/used/",
"http://niello.porschedealer.com/specials/used/",
"http://porschefresno.com/specials/used/",
"http://porschesantabarbara.com/specials/used/",
"http://rancho-mirage.porschedealer.com/specials/used/",
"http://reno.porschedealer.com/specials/used/",
"http://rusnak-pasadena.porschedealer.com/specials/used/",
"http://rusnak-westlake.porschedealer.com/specials/used/",
"http://scottsdale.porschedealer.com/specials/used/",
"http://sonnenporsche.com/specials/used/",
"http://spokane.porschedealer.com/specials/used/",
"http://stevens-creek.porschedealer.com/specials/used/",
"http://stevinson.porschedealer.com/specials/used/",
"http://tucson.porschedealer.com/specials/used/",
"https://bellingham.porschedealer.com/specials/used/",
"https://beverlyhillsporsche.com/specials/used/",
"https://burlingame.porschedealer.com/specials/used/",
"https://chandler.porschedealer.com/specials/used/",
"https://circleporsche.com/specials/used/",
"https://gaudinporschelv.com/specials/used/",
"https://hoehnporsche.com/specials/used/",
"https://porschelehi.com/specials/used/",
"https://porscheofanchorage.com/specials/used/",
"https://porscheofsandiego.com/specials/used/",
"https://porscheoftacoma.com/specials/used/",
"https://porschesaltlakecity.com/specials/used/",
"https://porschesouthbay.com/specials/used/",
"https://prestigeimportsporsche.com/specials/used/",
"https://riverside.porschedealer.com/specials/used/",
"https://sunsetporsche.com/specials/used/",
"https://walnutcreek.porschedealer.com/specials/used/",

//Service Specials URLs
"http://albuquerque.porschedealer.com/specials/service/",
"http://autogallery.porschedealer.com/specials/service/",
"http://bakersfield.porschedealer.com/specials/service/",
"http://bellevue.porschedealer.com/specials/service/",
"http://bend.porschedealer.com/specials/service/",
"http://boise.porschedealer.com/specials/service/",
"http://carlsen.porschedealer.com/specials/service/",
"http://colorado-springs.porschedealer.com/specials/service/",
"http://downtown-la.porschedealer.com/specials/service/",
"http://ed-carroll.porschedealer.com/specials/service/",
"http://fremont.porschedealer.com/specials/service/",
"http://hawaii.porschedealer.com/specials/service/",
"http://livermore.porschedealer.com/specials/service/",
"http://mckenna.porschedealer.com/specials/service/",
"http://monterey.porschedealer.com/specials/service/",
"http://newport-beach.porschedealer.com/specials/service/",
"http://niello.porschedealer.com/specials/service/",
"http://porschefresno.com/specials/service/",
"http://porschesantabarbara.com/specials/service/",
"http://rancho-mirage.porschedealer.com/specials/service/",
"http://reno.porschedealer.com/specials/service/",
"http://rusnak-pasadena.porschedealer.com/specials/service/",
"http://rusnak-westlake.porschedealer.com/specials/service/",
"http://scottsdale.porschedealer.com/specials/service/",
"http://sonnenporsche.com/specials/service/",
"http://spokane.porschedealer.com/specials/service/",
"http://stevens-creek.porschedealer.com/specials/service/",
"http://stevinson.porschedealer.com/specials/service/",
"http://tucson.porschedealer.com/specials/service/",
"https://bellingham.porschedealer.com/specials/service/",
"https://beverlyhillsporsche.com/specials/service/",
"https://burlingame.porschedealer.com/specials/service/",
"https://chandler.porschedealer.com/specials/service/",
"https://circleporsche.com/specials/service/",
"https://gaudinporschelv.com/specials/service/",
"https://hoehnporsche.com/specials/service/",
"https://porschelehi.com/specials/service/",
"https://porscheofanchorage.com/specials/service/",
"https://porscheofsandiego.com/specials/service/",
"https://porscheoftacoma.com/specials/service/",
"https://porschesaltlakecity.com/specials/service/",
"https://porschesouthbay.com/specials/service/",
"https://prestigeimportsporsche.com/specials/service/",
"https://riverside.porschedealer.com/specials/service/",
"https://sunsetporsche.com/specials/service/",
"https://walnutcreek.porschedealer.com/specials/service/",

//Parts Specials URLs
"http://albuquerque.porschedealer.com/specials/parts/",
"http://autogallery.porschedealer.com/specials/parts/",
"http://bakersfield.porschedealer.com/specials/parts/",
"http://bellevue.porschedealer.com/specials/parts/",
"http://bend.porschedealer.com/specials/parts/",
"http://boise.porschedealer.com/specials/parts/",
"http://carlsen.porschedealer.com/specials/parts/",
"http://colorado-springs.porschedealer.com/specials/parts/",
"http://downtown-la.porschedealer.com/specials/parts/",
"http://ed-carroll.porschedealer.com/specials/parts/",
"http://fremont.porschedealer.com/specials/parts/",
"http://hawaii.porschedealer.com/specials/parts/",
"http://livermore.porschedealer.com/specials/parts/",
"http://mckenna.porschedealer.com/specials/parts/",
"http://monterey.porschedealer.com/specials/parts/",
"http://newport-beach.porschedealer.com/specials/parts/",
"http://niello.porschedealer.com/specials/parts/",
"http://porschefresno.com/specials/parts/",
"http://porschesantabarbara.com/specials/parts/",
"http://rancho-mirage.porschedealer.com/specials/parts/",
"http://reno.porschedealer.com/specials/parts/",
"http://rusnak-pasadena.porschedealer.com/specials/parts/",
"http://rusnak-westlake.porschedealer.com/specials/parts/",
"http://scottsdale.porschedealer.com/specials/parts/",
"http://sonnenporsche.com/specials/parts/",
"http://spokane.porschedealer.com/specials/parts/",
"http://stevens-creek.porschedealer.com/specials/parts/",
"http://stevinson.porschedealer.com/specials/parts/",
"http://tucson.porschedealer.com/specials/parts/",
"https://bellingham.porschedealer.com/specials/parts/",
"https://beverlyhillsporsche.com/specials/parts/",
"https://burlingame.porschedealer.com/specials/parts/",
"https://chandler.porschedealer.com/specials/parts/",
"https://circleporsche.com/specials/parts/",
"https://gaudinporschelv.com/specials/parts/",
"https://hoehnporsche.com/specials/parts/",
"https://porschelehi.com/specials/parts/",
"https://porscheofanchorage.com/specials/parts/",
"https://porscheofsandiego.com/specials/parts/",
"https://porscheoftacoma.com/specials/parts/",
"https://porschesaltlakecity.com/specials/parts/",
"https://porschesouthbay.com/specials/parts/",
"https://prestigeimportsporsche.com/specials/parts/",
"https://riverside.porschedealer.com/specials/parts/",
"https://sunsetporsche.com/specials/parts/",
"https://walnutcreek.porschedealer.com/specials/parts/"];
// //
// //
// //
// //
// //
// //
// //
// // //
// // //
// // //
// // //
// // //
// // //
// // //
// // //



module.exports = specialsURLs;
